project:
  type: website
  output-dir: docs

website:
  title: "Anna VanAlstine"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css
    toc: true



